### ISSUE TITLE
Creating a production tool for scaling crop-mask predictions

### ISSUE THREAD

**Issue by cbur24** [digitalearthafrica/crop-mask#1]
In order for users to move efficiently from testing crop mask models within a notebook environment, into scaling classifications to entire Agro-Ecological Zones (AEZ), we need to build a suite of relatively easy-to-use scaling tools.

The final product should have a number of features:
1. Be relatively straight-forward to use:
        -  Require no interaction with source code
        -  A small number of user inputs (feature layer function, model path, tile-geojson, file export name)
        -  Interaction with the tool should occur within a familiar environment e.g. command line, or a jupyter notebook
2.  The code should export Cloud-Optimized Geotiffs in a manner that allows for indexing into the Open Data Cube. i.e. it should follow the correct file path and naming conventions, and contain the correct STAC metadata (I assume this part will not generalize beyond the crop-mask, but that's okay).
3.  Excellent documentation, with examples, is an important feature
4. While the first iteration of this tool will likely serially loop through a set of polygon tile boundaries in the input geojson, the code should be written in a way that ensures easy translation into an AWS SQS system that can run tiles in parallel across multiple instances (this will be necessary for classifying large AEZs in a reasonable amount of time).
5. While this tool is mostly specific to the crop-mask, if we can build them as modular and as generic as possible then they could prove useful for other product development projects.

pseudo code notebook to capture the ambition is located [here](https://github.com/digitalearthafrica/crop-mask/blob/feature/add-ai-code-for-production/dea_ml/docs/psuedo_code_template.ipynb)

**Comment by cbur24** [comment]
@fivejjs Something I didn't consider above.  Post-process masking (like we do with WOfS and elevation in the Eastern crop-mask) could be difficult to incorporate....Perhaps an optional post-process function as a user input could be one option?

**Comment by fivejjs** [comment]
working on that after the current branch?

**Comment by fivejjs** [comment]
resolved for current stage. I will open new one wit the new semiannual data access approach.
